### ISSUE TITLE
kubeconfig file shows error while deploying to aks using actions

### ISSUE THREAD

**Issue by vivishno** [Azure/aks-set-context#13]
While running a workflow used to deploy to azure kubernetes setting the context and then deploying to aks using k8-deploy action gives below error-
Error->
**##[error]YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 85:
     ... able. This is insecure. Location: /home/runner/work/_temp/kubeco ...** 

Have attached workflow steps used and detailed logs of action run
Workflow file used->[workflowfile.txt](https://github.com/Azure/aks-set-context/files/5298492/workflowfile.txt)

Detailed logs->[logs.txt](https://github.com/Azure/aks-set-context/files/5298491/logs.txt)

**Comment by ds-ms** [comment]
Looks like we have one more occurrence: https://github.com/Azure/actions/issues/48

**Comment by ds-ms** [comment]
@shigupt202 could you take a look?

**Comment by shigupt202** [comment]
This problem was because of the security warning introduced in latest Helm releases, as a result of which the baked manifest getting generated by the workflow contained the warning message. I'll change the kubeconfig file's permissions to fix this. In the meantime, customers can continue to use the action with older Helm releases (v3.3.1 or before).

**Comment by greenie-msft** [comment]
Sorry @shigupt202, I'm a little unclear on where the Helm version should be set, Can you clarify where exactly we should specify that? I'm not seeing that as a property in the deploy action itself.

**Comment by shigupt202** [comment]
@greenie-msft The problem is not with aks-set-context or k8s-deploy. The error message is actually coming because the manifest file generated by helm command in k8s-bake action contain the security warning. You should be having the same issue, assuming there's a k8s-bake step present in your workflow.

**Comment by greenie-msft** [comment]
Thanks for the reply @shigupt202. Yes, we are using the k8s-bake action alongside the deploy which is using helm2 as the render engine. 

Above you mentioned using Helm v3.3.1 or before. Looks like this issue is also present with Helm 2?

**Comment by shigupt202** [comment]
You can check the Helm releases to identify which versions have the problem. I believe more than one month old releases should be fine.

**Comment by shigupt202** [comment]
Also, if you have not specified any version for Helm in the action, by default it fetches the latest. `helm2` doesn't necessarily mean that the version is 2.x (The input name is misleading). Please verify that as well.
